INSERT INTO ih_proj4Stop VALUES(0,'Addison Road','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(1,'Anacostia','Green');
INSERT INTO ih_proj4Stop VALUES(2,'Archives','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(3,'Arlington Cemetery','Blue');
INSERT INTO ih_proj4Stop VALUES(4,'Ballston-MU','Orange');
INSERT INTO ih_proj4Stop VALUES(5,'Benning Road','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(6,'Bethesda','Red');
INSERT INTO ih_proj4Stop VALUES(7,'Braddock Road','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(8,'Branch Avenue','Green');
INSERT INTO ih_proj4Stop VALUES(9,'Brookland-CUA','Red');
INSERT INTO ih_proj4Stop VALUES(10,'Capitol Heights','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(11,'Capitol South','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(12,'Cheverly','Orange');
INSERT INTO ih_proj4Stop VALUES(13,'Clarendon','Orange');
INSERT INTO ih_proj4Stop VALUES(14,'Cleveland Park','Red');
INSERT INTO ih_proj4Stop VALUES(15,'College Park - University of Maryland','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(16,'Columbia Heights','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(17,'Congress Heights','Green');
INSERT INTO ih_proj4Stop VALUES(18,'Court House','Orange');
INSERT INTO ih_proj4Stop VALUES(19,'Crystal City','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(20,'Deanwood','Orange');
INSERT INTO ih_proj4Stop VALUES(21,'Dunn Loring','Orange');
INSERT INTO ih_proj4Stop VALUES(22,'Dupont Circle','Red');
INSERT INTO ih_proj4Stop VALUES(23,'East Falls Church','Orange');
INSERT INTO ih_proj4Stop VALUES(24,'Easter Market','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(25,'Eisenhower Avenue','Yellow');
INSERT INTO ih_proj4Stop VALUES(26,'Farragut North','Red');
INSERT INTO ih_proj4Stop VALUES(27,'Farragut West','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(28,'Federal Center SW','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(29,'Federal Triangle','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(30,'Foggy Bottom - GWU','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(31,'Forest Glen','Red');
INSERT INTO ih_proj4Stop VALUES(32,'Fort Totten','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(33,'Fort Totten','Red');
INSERT INTO ih_proj4Stop VALUES(34,'Franconia-Springfield','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(35,'Friendship Heights','Red');
INSERT INTO ih_proj4Stop VALUES(36,'Gallery Place','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(37,'Gallery Place','Red');
INSERT INTO ih_proj4Stop VALUES(38,'Georgia Avenue - Petworth','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(39,'Glenmont','Red');
INSERT INTO ih_proj4Stop VALUES(40,'Greenbelt','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(41,'Grosvenor-Strathmore','Red');
INSERT INTO ih_proj4Stop VALUES(42,'Huntington','Yellow');
INSERT INTO ih_proj4Stop VALUES(43,'Judiciary Square','Red');
INSERT INTO ih_proj4Stop VALUES(44,'King Street - Old Town','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(45,'L\'Enfent Plaza','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(46,'L\'Enfent Plaza','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(47,'Landover','Orange');
INSERT INTO ih_proj4Stop VALUES(48,'Largo Town Center','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(49,'McPherson Square','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(50,'Medical Center','Red');
INSERT INTO ih_proj4Stop VALUES(51,'Metro Center','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(52,'Metro Center','Red');
INSERT INTO ih_proj4Stop VALUES(53,'Minnesota Avenue','Orange');
INSERT INTO ih_proj4Stop VALUES(54,'Morgan Boulevard','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(55,'Mount Vernon Square','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(56,'Navy Yard - Ballpark','Green');
INSERT INTO ih_proj4Stop VALUES(57,'Naylor Road','Green');
INSERT INTO ih_proj4Stop VALUES(58,'New Caroollton','Orange');
INSERT INTO ih_proj4Stop VALUES(59,'NoMa - Gallaudet University','Red');
INSERT INTO ih_proj4Stop VALUES(60,'Pentagon','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(61,'Pentagon City','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(62,'Potomac Avenue','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(63,'Prince George\'s Plaza','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(64,'Rhode Island Avenue - Brentwood','Red');
INSERT INTO ih_proj4Stop VALUES(65,'Rockville','Red');
INSERT INTO ih_proj4Stop VALUES(66,'Ronald Reagan Washington National Airport','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(67,'Rosslyn','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(68,'Shady Grove','Red');
INSERT INTO ih_proj4Stop VALUES(69,'Shaw-Howard University','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(70,'Silver Spring','Red');
INSERT INTO ih_proj4Stop VALUES(71,'Smithsonian','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(72,'Southern Avenue','Green');
INSERT INTO ih_proj4Stop VALUES(73,'Stadium-Armory','Blue,Orange');
INSERT INTO ih_proj4Stop VALUES(74,'Suitland','Green');
INSERT INTO ih_proj4Stop VALUES(75,'Takoma','Red');
INSERT INTO ih_proj4Stop VALUES(76,'Tenleytown-AU','Red');
INSERT INTO ih_proj4Stop VALUES(77,'Twinbrook','Red');
INSERT INTO ih_proj4Stop VALUES(78,'U Street','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(79,'Union Station','Red');
INSERT INTO ih_proj4Stop VALUES(80,'Van Dorn Street','Blue,Yellow');
INSERT INTO ih_proj4Stop VALUES(81,'Van Ness - UDC','Red');
INSERT INTO ih_proj4Stop VALUES(82,'Vienna','Orange');
INSERT INTO ih_proj4Stop VALUES(83,'Virginia Square - GMU','Orange');
INSERT INTO ih_proj4Stop VALUES(84,'Waterfront','Green');
INSERT INTO ih_proj4Stop VALUES(85,'West Falls Church','Orange');
INSERT INTO ih_proj4Stop VALUES(86,'West Hyattsville','Green,Yellow');
INSERT INTO ih_proj4Stop VALUES(87,'Wheaton','Red');
INSERT INTO ih_proj4Stop VALUES(88,'White Flint','Red');
INSERT INTO ih_proj4Stop VALUES(89,'Woodley Park','Red');